name: Build
on:
  pull_request:
    branches:
      - 'dev'
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
          
